// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: jobgo.proto

package jobgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Cron         string `protobuf:"bytes,3,opt,name=Cron,proto3" json:"Cron,omitempty"`
	Func         string `protobuf:"bytes,4,opt,name=Func,proto3" json:"Func,omitempty"`
	Status       string `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	UpdatedOnUtc int64  `protobuf:"varint,6,opt,name=UpdatedOnUtc,proto3" json:"UpdatedOnUtc,omitempty"`
	CreatedOnUtc int64  `protobuf:"varint,7,opt,name=CreatedOnUtc,proto3" json:"CreatedOnUtc,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobgo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobgo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobgo_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Job) GetFunc() string {
	if x != nil {
		return x.Func
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetUpdatedOnUtc() int64 {
	if x != nil {
		return x.UpdatedOnUtc
	}
	return 0
}

func (x *Job) GetCreatedOnUtc() int64 {
	if x != nil {
		return x.CreatedOnUtc
	}
	return 0
}

var File_jobgo_proto protoreflect.FileDescriptor

var file_jobgo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01,
	0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x72, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x72, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x75, 0x6e,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x55, 0x74, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x55, 0x74, 0x63, 0x12, 0x22, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x55, 0x74, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x55, 0x74,
	0x63, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4c, 0x75, 0x6b, 0x69, 0x79, 0x61, 0x2f, 0x6a, 0x6f, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobgo_proto_rawDescOnce sync.Once
	file_jobgo_proto_rawDescData = file_jobgo_proto_rawDesc
)

func file_jobgo_proto_rawDescGZIP() []byte {
	file_jobgo_proto_rawDescOnce.Do(func() {
		file_jobgo_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobgo_proto_rawDescData)
	})
	return file_jobgo_proto_rawDescData
}

var file_jobgo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jobgo_proto_goTypes = []interface{}{
	(*Job)(nil), // 0: Job
}
var file_jobgo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobgo_proto_init() }
func file_jobgo_proto_init() {
	if File_jobgo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jobgo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobgo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobgo_proto_goTypes,
		DependencyIndexes: file_jobgo_proto_depIdxs,
		MessageInfos:      file_jobgo_proto_msgTypes,
	}.Build()
	File_jobgo_proto = out.File
	file_jobgo_proto_rawDesc = nil
	file_jobgo_proto_goTypes = nil
	file_jobgo_proto_depIdxs = nil
}
